#!/bin/env bash

if [ ! -f ~/.bashrc.bkp ]; then
	mv ~/.bashrc ~/.bashrc.bkp
fi

stow alacritty/ bash/ dunst/ emacs/ gtk-3.0/ nvim/ others/ picom/ qtile/ i3/ i3status-rust/ rofi/ starship/ terminator/ tmux/ utils/ zathura/ --adopt
