#!/usr/bin/env bash

backup() {
    echo "backup files"

    for file in aliases bash_profile bashrc env functions profile; do
        if [ -f "$HOME/.$file" ] && [ ! -L "$HOME/.$file" ]; then
            mv "$HOME/.$file" "$HOME/.$file.bkp"
        fi
    done
}

install() {
    echo "install configurations"
    dir=$(dirname $0)
    stow_config="--dir=$dir --target=$HOME --dotfiles"

    echo "stow configuration: " $stow_config
    echo $stow_config > $dir/.stowrc

    stow alacritty/ terminator/ bash/ dunst/ emacs/ gtk-3.0/ nvim/ others/ picom/ rofi/ starship/ tmux/ utils/ zathura/ bspwm/ polybar/ sxhkd/ wallpaper/ xmanager/ networkmanager-dmenu/ clang/ ranger/
    echo "done"
}

uninstall() {
    echo "uninstall configurations"
    stow -D alacritty/ terminator/ bash/ dunst/ emacs/ gtk-3.0/ nvim/ others/ picom/ rofi/ starship/ tmux/ utils/ zathura/ bspwm/ polybar/ sxhkd/ wallpaper/ xmanager/ networkmanager-dmenu/ clang/ ranger/
    echo "done"
}

usage() {
    echo -e "\nUsage:\n"
    echo -e "i - to install and configure"
    echo -e "u - to remove all configurations"
}

main() {
    case "$1" in
        i)  backup
            install
            ;;
        u) uninstall 
            ;;
        *) usage; exit 1;
    esac
}

main "$1"
