#!/bin/env bash

if [ ! -f ~/.bashrc.bkp ]; then
	mv ~/.bashrc ~/.bashrc.bkp
fi

stow alacritty/ bash/ dunst/ emacs/ gtk-3.0/ nvim/ others/ picom/ rofi/ starship/ tmux/ utils/ zathura/ bspwm/ polybar/ sxhkd/ wallpaper/ xmanager/ networkmanager-dmenu/ --adopt
