# ~/.config/starship.toml

[character]
error_symbol = "[💔 ➜](bold red) "
success_symbol = "[🖥 ➜](bold green)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
#format = "★★ [$path]($style)[$lock_symbol]($lock_style) "
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "🌿 "
style = "bold blue"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🔴 "
ahead = "🔺×${count} "
behind = "🔻×${count} "
diverged = "🔀 🔺×${ahead_count} 🔻×${behind_count} "
untracked = "🔍×${count} "
stashed = "📥 "
modified = "🔓×${count} "
staged = "🔒×${count} "
renamed = "✨×${count} "
deleted = "🔥×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[package]
disabled = true

[c]
format = "via [$name $version]($style)"
detect_extensions = ["c", "h", "cpp", "hpp"]
style = "bold red"

[cmake]
format = "via [$name $version]($style)"
detect_files = ["Makefile"]
style = "bold red"

[python]
disabled = true
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "[🕙 $time]($style) "
style = "bold bright-green"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false
