theme = "nord-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
[block.theme_overrides]
idle_bg = "#2E3440"
idle_fg = "#A0A6B2"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
[block.theme_overrides]
idle_bg = "#A3BE8C"
idle_fg = "#2E3440"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#5E81AC"
idle_fg = "#2E3440"

[[block]]
block = "sound"
on_click= "pavucontrol"
[block.theme_overrides]
idle_bg = "#EBCB8B"
idle_fg = "#2E3440"

[[block]]
block = "time"
interval = 5
format = "%d/%m %R"
[block.theme_overrides]
idle_bg = "#B48EAD"
idle_fg = "#2E3440"

[[block]]
block = "custom"
interval = 1
command = "keyboardlayout --get" 
on_click = "keyboardlayout --set"
[block.theme_overrides]
idle_bg = "#81A1C1"
idle_fg = "#2E3440"
