#!/bin/bash

killall sxhkd &
pkill -f dunst &
pkill -f polybar &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width      1
bspc config window_gaps      12
bspc config split_ratio     0.5

bspc config click_to_focus           true
bspc config focus_follows_pointer    true
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config focus_by_distance true

bspc config top_padding          17
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0
bspc config border_width         1
bspc config window_gap           3

# colors
bspc config normal_border_color "#939ab7"
bspc config focused_border_color "#f5a97f"
bspc config urgent_border_color "#8aadf4"
bspc config presel_border_color "#8aadf4"

# Rules
bspc rule -a URxvt desktop='^1' state=tiled follow=on
bspc rule -a Emacs desktop='^2' state=tiled follow=on
bspc rule -a Firefox:Navigator desktop='^3' state=tiled follow=on
bspc rule -a Ferdium desktop='^4' state=tiled follow=on
bspc rule -a Org.gnome.Nautilus desktop='^5' state=tiled follow=on
bspc rule -a zoom desktop='^5' state=tiled follow=on
bspc rule -a Gimp desktop='^6' state=tiled follow=on
bspc rule -a Loading.. desktop='^2' state=floating follow=on
bspc rule -a Peek state=floating follow=on
bspc rule -a Transmission-gtk desktop='^5' state=floating follow=on

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

# Startup
feh --bg-scale $HOME/.config/wallpaper/wallpaper.jpg

pgrep -x sxhkd > /dev/null || sxhkd &

killall -q polybar &                  # Reboot polybar to correctly show workspaces
while pgrep -u $UID -x polybar >/dev/null; do sleep 1;done 

polybar main &

if [[ $(xrandr -q | grep 'DisplayPort-1 connected') ]]; then   # If second monitor, also enable second polybar
  bspc monitor DP1 -d 6 7 8 9 10
  bspc wm -O HDMI3 DP1
  polybar sec &
fi

xsetroot -cursor_name left_ptr
