#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config top_padding          20
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0
bspc config border_width         1
bspc config window_gap           8

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config split_ratio          0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity first_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a emacs desktop='^3' follow=on
bspc rule -a spotfy desktop='^5' follow=on
bspc rule -a thunar desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb ${HOME}/.Xresources

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-fill ~/.config/wallpaper/solar-system.jpg
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
