# bash_profile

if [ -f ~/.bashrc ]; then
   . ~/.bashrc
fi

# macos
case "$OSTYPE" in
    "darwin"*)
        echo "OSX"
        if [ -f $(brew --prefix)/etc/bash_completion ]; then
            . $(brew --prefix)/etc/bash_completion
        fi
        ;;
    "linux-gnu"*)
        if [ -f /etc/profile.d/bash_completion.sh ]; then
            . /etc/profile.d/bash_completion.sh
        fi
        ;;
    *)
        ;;
esac
