# bash_profile

if [ -f ~/.bashrc ]; then
   . ~/.bashrc
fi

# macos
if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

# linux
if [ -f /etc/profile.d/bash_completion.sh ]; then
   . /etc/profile.d/bash_completion.sh
fi
