require("plugins.dashboard")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.nvim-tree")
require("plugins.autopairs")
require("plugins.clangd")
